title: Netzwerk11
undertitle: für Flüchtlingshilfe
email: info.netzwerk11@web.de
description: >-
  Nachbarschftskreis Ahlem-Badenstedt-Davenstedt

baseurl: ""
url: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  news:
    permalink: news/:year:month:day/:title
    output: true
  projects:
    permalink: projekte/:year:month:day/:title
    output: true

include:
  - _pages

exclude:
  - /excludes
  - README.md
