title: Netzwerk11
undertitle: f端r Fl端chtlingshilfe
author: Rima
undertitle: f端r Fl端chtlingshilfe
email: info.netzwerk11@web.de
description: >-
  Nachbarschftskreis Ahlem-Badenstedt-Davenstedt

baseurl: ""
url: ""
permalink: :categories/:year:month:day/:title

# Build settings
theme: minima
plugins:
  - jekyll-feed

include:
  - _pages

exclude:
  - /excludes
  - README.md
